IglesiaBundle\Entity\RedesSociales:
    type: entity
    table: redes_sociales
    indexes:
        fk_redes_sociales_iglesia1_idx:
            columns:
                - iglesia_id
    id:
        url:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 15
            options:
                fixed: false
    manyToOne:
        iglesia:
            targetEntity: Iglesia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iglesia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
