IglesiaBundle\Entity\Rol:
    type: entity
    table: rol
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        permisos:
            type: json_array
            nullable: true
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
