IglesiaBundle\Entity\Subscriptor:
    type: entity
    table: subscriptor
    indexes:
        fk_IGLESIA_has_USUARIO_USUARIO1_idx:
            columns:
                - usurio_id
        fk_IGLESIA_has_USUARIO_IGLESIA1_idx:
            columns:
                - iglesia_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        suscrito:
            type: boolean
            nullable: true
    manyToOne:
        iglesia:
            targetEntity: Iglesia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iglesia_id:
                    referencedColumnName: id
            orphanRemoval: false
        usurio:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usurio_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
