IglesiaBundle\Entity\Telefonos:
    type: entity
    table: telefonos
    indexes:
        fk_telefonos_iglesia1_idx:
            columns:
                - iglesia_id
    id:
        telefono:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: true
            length: 6
            options:
                fixed: false
    manyToOne:
        iglesia:
            targetEntity: Iglesia
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                iglesia_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
